version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  api:
    build:
      context: .
      dockerfile: ./src/CoreApi/Dockerfile
    depends_on:
      - mongo
    ports:
      - "7001:7001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7001
      - CONNECTIONSTRINGS__MONGO=mongodb://mongo:27017
      - AZUREAD__INSTANCE=https://login.microsoftonline.com
      - AZUREAD__DOMAIN=<Domain>
      - AZUREAD__TENANTID=<TenantId>
      - AZUREAD__CLIENTID=<ClientId>

  client:
    build:
      context: .
      dockerfile: ./src/Client/Dockerfile
    depends_on:
      - api
    environment:
      - API_URL=http://api:7001
      - AZUREAD_CLIENTID=<ClientId>
      - AZUREAD_AUTHORITY=<Authority>
      - AZUREAD_REDIRECTURI=http://client:80
    ports:
      - "80:80"

volumes:
  data:
