version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  api:
    build:
      context: .
      dockerfile: ./src/CoreApi/Dockerfile
    depends_on:
      - mongo
    ports:
      - "7001:7001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7001
      - CONNECTIONSTRINGS__MONGO=mongodb://mongo:27017
      - AZUREAD__INSTANCE=https://login.microsoftonline.com
      - AZUREAD__DOMAIN=<domain>
      - AZUREAD__TENANTID=<teneant_id>
      - AZUREAD__CLIENTID=<client_id>

volumes:
  data:
