name: Post Package List Comment

on:
  pull_request:

jobs:
  post-package-list-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x' # Use the desired .NET version

      - name: List Packages
        run: |
          dotnet restore
          dotnet list package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Comment
        run: |
          COMMENT="```plaintext\n$(dotnet list package  --outdated)\n```"
          echo "::set-output name=comment::$COMMENT"
        id: comment

      - name: Comment on PR
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.comment.outputs.comment }}"
            })
