name: Check .NET Package Outdated
on:
  pull_request:
    branches:
      - main # Change this to match your main branch

jobs:
  outdated-packages:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x # You can specify the .NET version you want to use

    - name: Get Outdated Packages
      id: outdated
      run: |
        dotnet restore
        dotnet list package --outdated > outdated-packages.txt
      shell: bash

    - name: Post Comment
      if: ${{ always() }}
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const data = fs.readFileSync('outdated-packages.txt', 'utf8');
          const body = 'Outdated packages:\n```\n' + data + '\n```\n';
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
