name: Post PR Comment with dotnet list package output

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Install dependencies
      run: dotnet restore

    - name: List packages
      run: dotnet list package

    - name: Post PR Comment
      run: |
        COMMENT="```
        $(dotnet list package --outdated)
        ```"
        echo "$COMMENT" > comment.txt
        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat comment.txt)"
