name: Check Outdated .NET Packages

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  outdated-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x # Adjust to your desired .NET version

      - name: Install project dependencies
        run: dotnet restore

      - name: Check outdated packages
        run: |
          outdatedPackages=$(dotnet list package --outdated)
          echo "Outdated Packages:"
          echo "$outdatedPackages"
          echo "::set-output name=outdated-packages::$outdatedPackages"

      - name: Comment outdated packages
        uses: actions/github-script@v5
        with:
          script: |
            const outdatedPackages = '${{ steps.outdated-packages.outputs["outdated-packages"] }}';
            if (outdatedPackages.length > 0) {
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Outdated .NET packages:\n' + outdatedPackages,
              });
            }
